import type { Metadata } from "next";
import "./globals.css";
import { Providers } from './providers'

import { ColorModeScript } from "@chakra-ui/react";
import theme from './theme'
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>ShippingApp</title>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      </head>
      <body>
        <Providers>
          <Navigation>
            {children}
          </Navigation>
        </Providers>
      </body>
    </html>
  );
}
